function DFDL_copyright(~, ~)
  %# read text file lines as cell array of strings
  fid = fopen('README first.txt');
  str = textscan(fid, '%s', 'Delimiter','\n'); str = str{1};
  fclose(fid);

  hFig = figure('Visible', 'on', 'Position', [1400, 50, 750, 900]);   

  hPan = uipanel(hFig, ...
    'Title'   ,'', ...
    'Units'   ,'normalized', ...
    'Position',[0.05 0.05 0.9 0.9]);

  hEdit = uicontrol(hPan, ...
    'Style'              ,'edit', ...
    'FontSize'           ,9, ...
    'Min'                ,0, ...
    'Max'                ,2, ...
    'HorizontalAlignment','left', ...
    'FontSize'           , 12, ...
    'Units'              ,'normalized', ... 
    'Position'           ,[0 0 1 1], ...
    'String'             ,str);

  %# enable horizontal scrolling
  jEdit    = findjobj(hEdit);
  jEditbox = jEdit.getViewport().getComponent(0);
  jEditbox.setWrapping(false);                %# turn off word-wrapping
  jEditbox.setEditable(false);                %# non-editable
  set(jEdit,'HorizontalScrollBarPolicy',30);  %# HORIZONTAL_SCROLLBAR_AS_NEEDED

  %# maintain horizontal scrollbar policy which reverts back on component resize 
  hjEdit = handle(jEdit,'CallbackProperties');
  set(hjEdit, 'ComponentResizedCallback',...
      'set(gcbo,''HorizontalScrollBarPolicy'',30)');

end